# Complete User Flow E2E Test
#
# This workflow tests the complete user flow:
# 1. Land on home page
# 2. Navigate to workspaces
# 3. Create a new workspace
# 4. Get API token from settings
# 5. Run CLI with benchmark data
# 6. Verify results appear in UI

name: Complete User Flow E2E
description: Test the full user flow from landing to benchmark results

timeout: 120000

env:
  CLI_BINARY: ../target/release/rabbitbench
  API_URL: http://localhost:3000/api

jobs:
  complete-flow:
    name: Home -> Workspace -> API Token -> CLI -> Results
    steps:
      # ============================================
      # STEP 1: Land on home page
      # ============================================
      - name: Visit home page
        uses: navigate
        with:
          url: /
        assert:
          - type: visible
            selector:
              role: heading
              name: Benchmark Performance

      # ============================================
      # STEP 2: Navigate to workspaces
      # ============================================
      - name: Click Get Started button
        uses: click
        with:
          selector:
            role: button
            name: Get Started
          first: true

      - name: Verify workspaces page
        uses: wait
        with:
          url: /workspaces
        assert:
          - type: url
            equals: /workspaces
          - type: visible
            selector:
              role: heading
              name: Workspaces

      # ============================================
      # STEP 3: Create a new workspace
      # ============================================
      - name: Click New Workspace button
        uses: click
        with:
          selector:
            role: button
            name: New Workspace

      - name: Verify new workspace form
        uses: wait
        with:
          url: /workspaces/new
        assert:
          type: url
          equals: /workspaces/new

      - name: Generate unique slug
        id: workspace
        uses: store
        with:
          key: slug
          value: e2e-flow-${{ vars.timestamp }}

      - name: Fill workspace slug
        uses: fill
        with:
          selector:
            label: Slug
          value: ${{ vars.slug }}

      - name: Fill workspace name
        uses: fill
        with:
          selector:
            label: Name
          value: E2E Flow Test ${{ vars.timestamp }}

      - name: Fill workspace description
        uses: fill
        with:
          selector:
            label: Description
          value: E2E test workspace

      - name: Submit workspace form
        uses: click
        with:
          selector:
            role: button
            name: Create Workspace

      - name: Wait for workspace page
        uses: wait
        with:
          url: /workspaces/${{ vars.slug }}
          timeout: 15000
        assert:
          - type: url
            contains: ${{ vars.slug }}
          - type: visible
            selector:
              role: heading
              name: E2E Flow Test

      # ============================================
      # STEP 4: Navigate to settings and create API token
      # ============================================
      - name: Click Settings button
        uses: click
        with:
          selector:
            role: button
            name: Settings

      - name: Verify settings page
        uses: wait
        with:
          url: /workspaces/${{ vars.slug }}/settings
          timeout: 15000
        assert:
          type: visible
          selector:
            role: heading
            name: Settings

      - name: Fill token name
        uses: fill
        with:
          selector:
            placeholder: Token name
          value: E2E CLI Token ${{ vars.timestamp }}

      - name: Click Create Token button
        uses: click
        with:
          selector:
            role: button
            name: Create Token

      - name: Wait for token to appear
        uses: wait
        with:
          selector: code
          timeout: 10000

      - name: Click eye icon to show token
        uses: click
        with:
          selector: button:has(svg)
          first: true

      - name: Extract API token
        id: token
        uses: store
        with:
          key: apiToken
          selector: code
          regex: rb_[a-f0-9]{32}

      - name: Click Done button
        uses: click
        with:
          selector:
            role: button
            name: Done

      # ============================================
      # STEP 5: Run CLI with benchmark data
      # ============================================
      - name: Run CLI with mock benchmark
        uses: exec
        with:
          command: |
            TEMP_DIR=$(mktemp -d)
            SCRIPT="$TEMP_DIR/mock-benchmark.sh"
            cat > "$SCRIPT" << 'CRITERION_EOF'
            #!/bin/sh
            cat << 'EOF'
            Benchmarking e2e_test/operation1
            e2e_test/operation1     time:   [100.00 ns 110.00 ns 120.00 ns]
                                    change: [-0.5% +0.8% +2.3%] (p = 0.27 > 0.05)
                                    No change in performance detected.

            Benchmarking e2e_test/operation2
            e2e_test/operation2     time:   [1.5000 µs 1.6000 µs 1.7000 µs]
                                    change: [+1.0% +2.0% +3.0%] (p = 0.01 < 0.05)
                                    Performance has regressed.
            EOF
            CRITERION_EOF
            chmod +x "$SCRIPT"
            "${{ env.CLI_BINARY }}" run -p "${{ vars.slug }}" -b main --hash e2e123abc "$SCRIPT"
          env:
            RABBITBENCH_TOKEN: ${{ vars.apiToken }}
            RABBITBENCH_API_URL: ${{ env.API_URL }}
          timeout: 30000
          storeOutput: cliOutput

      # ============================================
      # STEP 6: Verify results appear in UI
      # ============================================
      - name: Navigate back to workspace
        uses: navigate
        with:
          url: /workspaces/${{ vars.slug }}

      - name: Wait for workspace heading
        uses: wait
        with:
          selector:
            role: heading
            name: E2E Flow Test
          timeout: 10000

      - name: Click Reports tab
        uses: click
        with:
          selector:
            role: tab
            name: Reports

      - name: Wait for reports to load
        uses: wait
        with:
          timeout: 1000

      - name: Verify report with git hash is visible
        uses: wait
        with:
          selector:
            text: e2e123
          timeout: 10000
        assert:
          - type: visible
            selector:
              text: e2e123
          - type: visible
            selector:
              text: main
